//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurochkin_ProductSchool
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Windows;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductPhotoes = new HashSet<ProductPhoto>();
            this.ProductSales = new HashSet<ProductSale>();
            this.Product1 = new HashSet<Product>();
            this.Products = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public decimal Cost { get; set; }
        public string Description { get; set; }
        public string MainImagePath { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ManufacturerID { get; set; }

        public string PriceWithCurrency
        {
            get
            {
                return $"{Convert.ToDouble(Cost)} рублей";
            }
        }

        public Visibility VisibilityActive
        {
            get
            {
                if (IsActive) return Visibility.Hidden;
                return Visibility.Visible;
            }
        }

        public byte[] ImageAddress
        {
            get
            {
                if (File.Exists($"{MainImagePath}")) 
                    return File.ReadAllBytes($"{MainImagePath}");
                return null;
            }
        }

        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPhoto> ProductPhotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
